---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
        labels:
          app: "prometheus"

  - job_name: 'django'
    metrics_path: 'prometheus/metrics'
    static_configs:
      - targets: ['web:8000']
        labels:
          app: 'django'

  - job_name: 'worker'
    static_configs:
      - targets: ['celery-exporter:9808']
        labels:
          app: 'worker'
       