services:
  web:
    command: /start-web-dev.sh
    volumes:
      - ./backend:/app
      - static_data:/app/staticfiles

  worker:
    command: [ "celery", "-A", "conf.celery_app", "worker", "-l", "INFO" ]
    volumes:
      - ./backend:/app

volumes:
  static_data:
