[tool.black]
line-length = 99
target-version = ['py310', 'py311']
skip-string-normalization = true
extend-exclude = '''
/(
    conf
  | migrations
  | static
  | media
)/
'''

[tool.ruff]
line-length = 99
